# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Insights CI
          command: |
            curl -L https://be-vv-fwi-1233-cr.k8s.insights.fairwinds.com/v0/insights-ci-0.6.1.sh > insights-ci.sh
            echo "1c032ad6a9e70e58eb05ccdfbe17015e71d0c1f741aeecdd7548d7a6501c8175 *insights-ci.sh" | shasum -a 256 --check
            chmod +x insights-ci.sh
            image_version=build_6487 ./insights-ci.sh

workflows:
  build-workflow:
    jobs:
      - build
